"""agregar el campo unique en sesion_usuario: unique id_usuario

Revision ID: 06b30508bd16
Revises: b5d8f7e26a47
Create Date: 2026-09-19 14:43:00.720784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b30508bd16'
down_revision: Union[str, None] = 'b5d8f7e26a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sesion_usuario', ['id_usuario'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sesion_usuario', type_='unique')
    # ### end Alembic commands ###
